# Generated by Django 5.1.3 on 2024-11-30 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ocupacion', models.CharField(max_length=100)),
                ('descripcion_ocupa', models.TextField()),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.tienda')),
            ],
        ),
    ]
