# Generated by Django 5.1.3 on 2024-12-13 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_cargo_persona_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='canMaxima',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='productos',
            name='canMin',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(998)]),
        ),
    ]
